import { SignResult } from "./types";

export const realSigns: SignResult[] = [
  {
    "entryID": "angry",
    "lemmaID": "angry",
    "translation": "angry",
    "lexicalClass": "Adjective",
    "semanticField": "Emotion",
    "signType": "Symmetrical Or Alternating",
    "handshape": "5",
    "nondominantHandshape": "5",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": false,
    "location": "Body",
    "minorLocation": "Torso Top",
    "contact": true,
    "frequency": 4.96,
    "iconicity": 2.741,
    "complexity": 2,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/5.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=angry"
  },
  {
    "entryID": "bird",
    "lemmaID": "bird",
    "translation": "bird",
    "lexicalClass": "Noun",
    "semanticField": "Animal",
    "signType": "One Handed",
    "handshape": "g",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": null,
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Mouth",
    "contact": true,
    "frequency": 5.161,
    "iconicity": 4.553,
    "complexity": 1,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/g.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=bird"
  },
  {
    "entryID": "boss",
    "lemmaID": "boss",
    "translation": "boss",
    "lexicalClass": "Noun",
    "semanticField": "People",
    "signType": "One Handed",
    "handshape": "curved_5",
    "nondominantHandshape": null,
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Body",
    "minorLocation": "Shoulder",
    "contact": true,
    "frequency": 5.24,
    "iconicity": 1.8,
    "complexity": 1,
    "neighborhoodDensity": 4,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/curved_5.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=boss"
  },
  {
    "entryID": "corn_2",
    "lemmaID": "corn_2",
    "translation": "corn",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "Symmetrical Or Alternating",
    "handshape": "curved_5",
    "nondominantHandshape": "curved_5",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": null,
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Head Away",
    "contact": false,
    "frequency": 2.0,
    "iconicity": 3.692,
    "complexity": 1,
    "neighborhoodDensity": 4,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/curved_5.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=corn_2"
  },
  {
    "entryID": "dinosaur",
    "lemmaID": "dinosaur",
    "translation": "dinosaur",
    "lexicalClass": "Noun",
    "semanticField": "Animal",
    "signType": "One Handed",
    "handshape": "o",
    "nondominantHandshape": null,
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 2.333,
    "iconicity": 3.564,
    "complexity": 1,
    "neighborhoodDensity": 4,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/o.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=dinosaur"
  },
  {
    "entryID": "duck",
    "lemmaID": "duck",
    "translation": "duck",
    "lexicalClass": "Noun",
    "semanticField": "Animal",
    "signType": "One Handed",
    "handshape": "flat_h",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": null,
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Mouth",
    "contact": true,
    "frequency": 3.37,
    "iconicity": 4.5,
    "complexity": 2,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/flat_h.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=duck"
  },
  {
    "entryID": "engineer",
    "lemmaID": "engineer",
    "translation": "engineer",
    "lexicalClass": "Noun",
    "semanticField": "People",
    "signType": "Dominance Violation",
    "handshape": "y",
    "nondominantHandshape": "Dominance Condition Violation",
    "selectedFingers": "p",
    "numberSelected": 1,
    "indexSelected": false,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": null,
    "repeatedMovement": true,
    "location": "Hand",
    "minorLocation": "Finger Tip",
    "contact": true,
    "frequency": 3.48,
    "iconicity": 1.857,
    "complexity": 1,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/y.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=engineer"
  },
  {
    "entryID": "happy",
    "lemmaID": "happy",
    "translation": "happy",
    "lexicalClass": "Adjective",
    "semanticField": "Emotion",
    "signType": "One Handed",
    "handshape": "open_b",
    "nondominantHandshape": null,
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": true,
    "location": "Body",
    "minorLocation": "Torso Top",
    "contact": true,
    "frequency": 5.7,
    "iconicity": 3.25,
    "complexity": 2,
    "neighborhoodDensity": 4,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/open_b.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=happy"
  },
  {
    "entryID": "inside",
    "lemmaID": "inside",
    "translation": "inside",
    "lexicalClass": "Adjective",
    "semanticField": "Locative",
    "signType": "Asymmetrical Same Handshape",
    "handshape": "o",
    "nondominantHandshape": "o",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Hand",
    "minorLocation": "Other",
    "contact": true,
    "frequency": 5.536,
    "iconicity": 5.55,
    "complexity": 1,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/o.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=inside"
  },
  {
    "entryID": "italy",
    "lemmaID": "italy",
    "translation": "italy",
    "lexicalClass": "Name",
    "semanticField": "Place",
    "signType": "One Handed",
    "handshape": "curved_l",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Z-shaped",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 2.92,
    "iconicity": 1.733,
    "complexity": 3,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/curved_l.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=italy"
  },
  {
    "entryID": "japan",
    "lemmaID": "japan",
    "translation": "japan",
    "lexicalClass": "Name",
    "semanticField": "Place",
    "signType": "Symmetrical Or Alternating",
    "handshape": "g",
    "nondominantHandshape": "g",
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": true,
    "frequency": 2.565,
    "iconicity": 1.114,
    "complexity": 1,
    "neighborhoodDensity": 6,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/g.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=japan"
  },
  {
    "entryID": "lobster",
    "lemmaID": "lobster",
    "translation": "lobster",
    "lexicalClass": "Noun",
    "semanticField": "Animal",
    "signType": "Symmetrical Or Alternating",
    "handshape": "o",
    "nondominantHandshape": "o",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": null,
    "repeatedMovement": true,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 2.923,
    "iconicity": 4.833,
    "complexity": 1,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/o.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=lobster"
  },
  {
    "entryID": "mouse",
    "lemmaID": "mouse",
    "translation": "mouse",
    "lexicalClass": "Noun",
    "semanticField": "Animal",
    "signType": "One Handed",
    "handshape": "1",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Cheek Nose",
    "contact": true,
    "frequency": 3.36,
    "iconicity": 2.952,
    "complexity": 1,
    "neighborhoodDensity": 15,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/1.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=mouse"
  },
  {
    "entryID": "nephew",
    "lemmaID": "nephew",
    "translation": "nephew",
    "lexicalClass": "Noun",
    "semanticField": "People",
    "signType": "One Handed",
    "handshape": "flat_n",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": null,
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Head Away",
    "contact": false,
    "frequency": 2.621,
    "iconicity": 1.108,
    "complexity": 2,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/flat_n.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=nephew"
  },
  {
    "entryID": "new_york",
    "lemmaID": "new_york",
    "translation": "new york",
    "lexicalClass": "Noun",
    "semanticField": "Place",
    "signType": "Asymmetrical Different Handshape",
    "handshape": "y",
    "nondominantHandshape": "B",
    "selectedFingers": "p",
    "numberSelected": 1,
    "indexSelected": false,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Hand",
    "minorLocation": "Palm",
    "contact": true,
    "frequency": 3.68,
    "iconicity": 1.0,
    "complexity": 3,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/y.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=new_york"
  },
  {
    "entryID": "next_to",
    "lemmaID": "next_to",
    "translation": "next to",
    "lexicalClass": "Minor",
    "semanticField": "Locative",
    "signType": "Asymmetrical Same Handshape",
    "handshape": "flat_b",
    "nondominantHandshape": "flat_b",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": false,
    "location": "Hand",
    "minorLocation": "Finger Back",
    "contact": true,
    "frequency": 4.704,
    "iconicity": 5.382,
    "complexity": 2,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/flat_b.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=next_to"
  },
  {
    "entryID": "one",
    "lemmaID": "one",
    "translation": "one",
    "lexicalClass": "Noun",
    "semanticField": "Number",
    "signType": "One Handed",
    "handshape": "1",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 6.148,
    "iconicity": 6.97,
    "complexity": 1,
    "neighborhoodDensity": 22,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/1.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=one"
  },
  {
    "entryID": "onion",
    "lemmaID": "onion",
    "translation": "onion",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "One Handed",
    "handshape": "bent_1",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": null,
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Eye",
    "contact": true,
    "frequency": 5.28,
    "iconicity": 4.286,
    "complexity": 1,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/bent_1.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=onion"
  },
  {
    "entryID": "over",
    "lemmaID": "over",
    "translation": "over",
    "lexicalClass": "Minor",
    "semanticField": "Locative",
    "signType": "Asymmetrical Same Handshape",
    "handshape": "closed_b",
    "nondominantHandshape": "closed_b",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Curved",
    "repeatedMovement": false,
    "location": "Hand",
    "minorLocation": "Finger Radial",
    "contact": false,
    "frequency": 5.074,
    "iconicity": 0.0,
    "complexity": 2,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/closed_b.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=over"
  },
  {
    "entryID": "philadelphia",
    "lemmaID": "philadelphia",
    "translation": "philadelphia",
    "lexicalClass": "Name",
    "semanticField": "Place",
    "signType": "One Handed",
    "handshape": "p",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Back And Forth",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 3.37,
    "iconicity": 1.261,
    "complexity": 5,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/p.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=philadelphia"
  },
  {
    "entryID": "potato",
    "lemmaID": "potato",
    "translation": "potato",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "Asymmetrical Different Handshape",
    "handshape": "bent_v",
    "nondominantHandshape": "C",
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Hand",
    "minorLocation": "Palm Back",
    "contact": true,
    "frequency": 4.8,
    "iconicity": 1.143,
    "complexity": 3,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/bent_v.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=potato"
  },
  {
    "entryID": "russia_2",
    "lemmaID": "russia",
    "translation": "russia",
    "lexicalClass": "Name",
    "semanticField": "Place",
    "signType": "One Handed",
    "handshape": "1",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Back And Forth",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Mouth",
    "contact": true,
    "frequency": 3.111,
    "iconicity": 1.613,
    "complexity": 3,
    "neighborhoodDensity": 16,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/1.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=russia_2"
  },
  {
    "entryID": "sad",
    "lemmaID": "sad",
    "translation": "sad",
    "lexicalClass": "Adjective",
    "semanticField": "Emotion",
    "signType": "Symmetrical Or Alternating",
    "handshape": "5",
    "nondominantHandshape": "5",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Head Away",
    "contact": false,
    "frequency": 5.24,
    "iconicity": 5.8,
    "complexity": 1,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/5.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=sad"
  },
  {
    "entryID": "spaghetti",
    "lemmaID": "spaghetti",
    "translation": "spaghetti",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "Symmetrical Or Alternating",
    "handshape": "i",
    "nondominantHandshape": "i",
    "selectedFingers": "p",
    "numberSelected": 1,
    "indexSelected": false,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Circular",
    "repeatedMovement": true,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 3.935,
    "iconicity": 2.718,
    "complexity": 3,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/i.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=spaghetti"
  },
  {
    "entryID": "squirrel",
    "lemmaID": "squirrel",
    "translation": "squirrel",
    "lexicalClass": "Noun",
    "semanticField": "Animal",
    "signType": "Dominance Violation",
    "handshape": "bent_v",
    "nondominantHandshape": "Dominance Condition Violation",
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Hand",
    "minorLocation": "Finger Tip",
    "contact": true,
    "frequency": 2.8,
    "iconicity": 2.917,
    "complexity": 2,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/bent_v.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=squirrel"
  },
  {
    "entryID": "straight",
    "lemmaID": "straight",
    "translation": "straight",
    "lexicalClass": "Adjective",
    "semanticField": "Attribute",
    "signType": "One Handed",
    "handshape": "closed_b",
    "nondominantHandshape": null,
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Forehead",
    "contact": true,
    "frequency": 5.571,
    "iconicity": 6.16,
    "complexity": 1,
    "neighborhoodDensity": 8,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/closed_b.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=straight"
  },
  {
    "entryID": "strawberry",
    "lemmaID": "strawberry",
    "translation": "strawberry",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "One Handed",
    "handshape": "f",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Mouth",
    "contact": true,
    "frequency": 2.524,
    "iconicity": 1.595,
    "complexity": 1,
    "neighborhoodDensity": 7,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/f.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=strawberry"
  },
  {
    "entryID": "strawberry_2",
    "lemmaID": "strawberry_2",
    "translation": "strawberry",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "One Handed",
    "handshape": "f",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Mouth",
    "contact": true,
    "frequency": 5.667,
    "iconicity": 1.292,
    "complexity": 2,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/f.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=strawberry_2"
  },
  {
    "entryID": "strong",
    "lemmaID": "strong",
    "translation": "strong",
    "lexicalClass": "Adjective",
    "semanticField": "Attribute",
    "signType": "Symmetrical Or Alternating",
    "handshape": "s",
    "nondominantHandshape": "s",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Body",
    "minorLocation": "Body Away",
    "contact": false,
    "frequency": 4.926,
    "iconicity": 6.55,
    "complexity": 1,
    "neighborhoodDensity": 9,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/s.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=strong"
  },
  {
    "entryID": "stupid_1",
    "lemmaID": "stupid_1",
    "translation": "stupid",
    "lexicalClass": "Adjective",
    "semanticField": "Attribute",
    "signType": "One Handed",
    "handshape": "v",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Forehead",
    "contact": true,
    "frequency": 4.1,
    "iconicity": 3.767,
    "complexity": 2,
    "neighborhoodDensity": 3,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/v.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=stupid_1"
  },
  {
    "entryID": "stupid_2",
    "lemmaID": "stupid_2",
    "translation": "stupid",
    "lexicalClass": "Adjective",
    "semanticField": "Attribute",
    "signType": "One Handed",
    "handshape": "g",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": null,
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Head Away",
    "contact": false,
    "frequency": 4.633,
    "iconicity": 4.161,
    "complexity": 1,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/g.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=stupid_2"
  },
  {
    "entryID": "sushi",
    "lemmaID": "sushi",
    "translation": "sushi",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "Asymmetrical Different Handshape",
    "handshape": "h",
    "nondominantHandshape": "B",
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Hand",
    "minorLocation": "Palm",
    "contact": true,
    "frequency": 4.269,
    "iconicity": 1.32,
    "complexity": 3,
    "neighborhoodDensity": 7,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/h.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=sushi"
  },
  {
    "entryID": "sweep",
    "lemmaID": "sweep",
    "translation": "sweep",
    "lexicalClass": "Verb",
    "semanticField": "Event",
    "signType": "Asymmetrical Same Handshape",
    "handshape": "open_b",
    "nondominantHandshape": "open_b",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": true,
    "location": "Hand",
    "minorLocation": "Palm",
    "contact": true,
    "frequency": 3.259,
    "iconicity": 4.6,
    "complexity": 2,
    "neighborhoodDensity": 11,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/open_b.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=sweep"
  },
  {
    "entryID": "third_1",
    "lemmaID": "third",
    "translation": "third",
    "lexicalClass": "Number",
    "semanticField": "Number",
    "signType": "One Handed",
    "handshape": "3",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": null,
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 4.481,
    "iconicity": 4.065,
    "complexity": 2,
    "neighborhoodDensity": 3,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/3.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=third_1"
  },
  {
    "entryID": "third_2",
    "lemmaID": "third",
    "translation": "third",
    "lexicalClass": "Number",
    "semanticField": "Number",
    "signType": "One Handed",
    "handshape": "3",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 4.4,
    "iconicity": 3.36,
    "complexity": 3,
    "neighborhoodDensity": 3,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/3.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=third_2"
  },
  {
    "entryID": "three",
    "lemmaID": "three",
    "translation": "three",
    "lexicalClass": "Number",
    "semanticField": "Number",
    "signType": "One Handed",
    "handshape": "3",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 6.08,
    "iconicity": 6.667,
    "complexity": 2,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/3.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=three"
  },
  {
    "entryID": "tiger",
    "lemmaID": "tiger",
    "translation": "tiger",
    "lexicalClass": "Noun",
    "semanticField": "Animal",
    "signType": "Symmetrical Or Alternating",
    "handshape": "5",
    "nondominantHandshape": "5",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Cheek Nose",
    "contact": false,
    "frequency": 3.097,
    "iconicity": 3.711,
    "complexity": 1,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/5.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=tiger"
  },
  {
    "entryID": "twins_1",
    "lemmaID": "twins",
    "translation": "twins",
    "lexicalClass": "Noun",
    "semanticField": "People",
    "signType": "One Handed",
    "handshape": "v",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Z-shaped",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Chin",
    "contact": true,
    "frequency": 3.4,
    "iconicity": 2.273,
    "complexity": 4,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/v.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=twins_1"
  },
  {
    "entryID": "twins_2",
    "lemmaID": "twins",
    "translation": "twins",
    "lexicalClass": "Noun",
    "semanticField": "People",
    "signType": "One Handed",
    "handshape": "baby_o",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Z-shaped",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Chin",
    "contact": true,
    "frequency": 3.04,
    "iconicity": 1.48,
    "complexity": 3,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/baby_o.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=twins_2"
  },
  {
    "entryID": "two",
    "lemmaID": "two",
    "translation": "two",
    "lexicalClass": "Number",
    "semanticField": "Number",
    "signType": "One Handed",
    "handshape": "v",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 5.286,
    "iconicity": 6.963,
    "complexity": 2,
    "neighborhoodDensity": 7,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/v.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=two"
  },
  {
    "entryID": "under",
    "lemmaID": "under",
    "translation": "under",
    "lexicalClass": "Minor",
    "semanticField": "Locative",
    "signType": "Asymmetrical Different Handshape",
    "handshape": "a",
    "nondominantHandshape": "B",
    "selectedFingers": "t",
    "numberSelected": 1,
    "indexSelected": false,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": true,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": false,
    "location": "Hand",
    "minorLocation": "Hand Away",
    "contact": false,
    "frequency": 4.406,
    "iconicity": 3.968,
    "complexity": 4,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/a.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=under"
  },
  {
    "entryID": "vacuum",
    "lemmaID": "vacuum",
    "translation": "vacuum",
    "lexicalClass": "Verb",
    "semanticField": "Event",
    "signType": "One Handed",
    "handshape": "baby_o",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Z-shaped",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 3.692,
    "iconicity": 4.52,
    "complexity": 3,
    "neighborhoodDensity": 7,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/baby_o.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=vacuum"
  },
  {
    "entryID": "vegetable",
    "lemmaID": "vegetable",
    "translation": "vegetable",
    "lexicalClass": "Noun",
    "semanticField": "Food",
    "signType": "One Handed",
    "handshape": "v",
    "nondominantHandshape": null,
    "selectedFingers": "im",
    "numberSelected": 2,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": null,
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Mouth",
    "contact": true,
    "frequency": 4.931,
    "iconicity": 1.2,
    "complexity": 2,
    "neighborhoodDensity": 1,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/v.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=vegetable"
  },
  {
    "entryID": "waiter",
    "lemmaID": "waiter",
    "translation": "waiter",
    "lexicalClass": "Noun",
    "semanticField": "People",
    "signType": "Symmetrical Or Alternating",
    "handshape": "open_b",
    "nondominantHandshape": "open_b",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 4.484,
    "iconicity": 1.568,
    "complexity": 0,
    "neighborhoodDensity": 36,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/open_b.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=waiter"
  },
  {
    "entryID": "wander",
    "lemmaID": "wander",
    "translation": "wander",
    "lexicalClass": "Verb",
    "semanticField": "Event",
    "signType": "One Handed",
    "handshape": "1",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Closed",
    "movement": "Z-shaped",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 3.548,
    "iconicity": 3.487,
    "complexity": 3,
    "neighborhoodDensity": 15,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/1.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=wander"
  },
  {
    "entryID": "wet",
    "lemmaID": "wet",
    "translation": "wet",
    "lexicalClass": "Adjective",
    "semanticField": "Attribute",
    "signType": "Symmetrical Or Alternating",
    "handshape": "5",
    "nondominantHandshape": "5",
    "selectedFingers": "imrp",
    "numberSelected": 4,
    "indexSelected": true,
    "middleSelected": true,
    "ringSelected": true,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": false,
    "frequency": 4.52,
    "iconicity": 1.7,
    "complexity": 1,
    "neighborhoodDensity": 2,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/5.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=wet"
  },
  {
    "entryID": "witch",
    "lemmaID": "witch",
    "translation": "witch",
    "lexicalClass": "Noun",
    "semanticField": "People",
    "signType": "One Handed",
    "handshape": "bent_l",
    "nondominantHandshape": null,
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Curved",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Head Away",
    "contact": true,
    "frequency": 1.739,
    "iconicity": 2.762,
    "complexity": 2,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/bent_l.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=witch"
  },
  {
    "entryID": "wrong_1",
    "lemmaID": "wrong",
    "translation": "wrong",
    "lexicalClass": "Adjective",
    "semanticField": "Attribute",
    "signType": "One Handed",
    "handshape": "y",
    "nondominantHandshape": null,
    "selectedFingers": "p",
    "numberSelected": 1,
    "indexSelected": false,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": true,
    "location": "Head",
    "minorLocation": "Chin",
    "contact": true,
    "frequency": 6.08,
    "iconicity": 1.889,
    "complexity": 2,
    "neighborhoodDensity": 6,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/y.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=wrong_1"
  },
  {
    "entryID": "wrong_2",
    "lemmaID": "wrong",
    "translation": "wrong",
    "lexicalClass": "Adjective",
    "semanticField": "Attribute",
    "signType": "One Handed",
    "handshape": "y",
    "nondominantHandshape": null,
    "selectedFingers": "p",
    "numberSelected": 1,
    "indexSelected": false,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": true,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Head",
    "minorLocation": "Chin",
    "contact": true,
    "frequency": 5.667,
    "iconicity": 1.389,
    "complexity": 2,
    "neighborhoodDensity": 3,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/y.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=wrong_2"
  },
  {
    "entryID": "zoom_in",
    "lemmaID": "zoom_in",
    "translation": "zoom in",
    "lexicalClass": "Verb",
    "semanticField": "Event",
    "signType": "Symmetrical Or Alternating",
    "handshape": "s",
    "nondominantHandshape": "s",
    "selectedFingers": "i",
    "numberSelected": 1,
    "indexSelected": true,
    "middleSelected": false,
    "ringSelected": false,
    "pinkySelected": false,
    "thumbSelected": false,
    "thumbPosition": "Open",
    "movement": "Straight",
    "repeatedMovement": false,
    "location": "Neutral",
    "minorLocation": "Neutral",
    "contact": true,
    "frequency": 3.958,
    "iconicity": 4.667,
    "complexity": 1,
    "neighborhoodDensity": 0,
    "handshapeImage": "https://aslcdi.website/images/handshape_images/s.png",
    "aslLexURL": "https://asl-lex.org/visualization/?sign=zoom_in"
  }
];
