import { NextRequest, NextResponse } from "next/server";

import { naturalLanguageToSparql } from "@/lib/nl-to-sparql";
import { validateSparql } from "@/lib/validate-sparql";
import { queryRealData } from "@/lib/query-real-data";
import { executeSparqlEndpoint } from "@/lib/sparql-endpoint";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const question = body.question?.trim();

    if (!question) {
      return NextResponse.json(
        { error: "Question is required." },
        { status: 400 }
      );
    }

    // Generate schema-grounded SPARQL
    const sparql = await naturalLanguageToSparql(question);

    // Validate before execution
    validateSparql(sparql);

    let results;
    let mode;
    let note;

    if (process.env.SPARQL_ENDPOINT_URL) {
      // Execute against the live RDF knowledge graph
      results = await executeSparqlEndpoint(sparql);

      mode = process.env.GROQ_API_KEY
        ? "LLM + live RDF knowledge graph"
        : "Schema-aware SPARQL + live RDF knowledge graph";

      note =
        "The generated SPARQL was executed against the configured RDF/SPARQL endpoint.";
    } else {
      // Use the real curated 50-sign dataset locally
      results = queryRealData(question);

      mode = process.env.GROQ_API_KEY
        ? "LLM + local 50-sign dataset"
        : "Local 50-sign dataset";

      note = process.env.GROQ_API_KEY
        ? "SPARQL is generated by GPT-OSS. Until a SPARQL endpoint is configured, results are retrieved from the supplied real 50-sign dataset."
        : "The application uses the supplied real 50-sign dataset with a schema-aware SPARQL generator. Add GROQ_API_KEY for LLM-based NL-to-SPARQL generation or SPARQL_ENDPOINT_URL for direct RDF knowledge graph execution.";
    }

    return NextResponse.json({
      question,
      sparql,
      count: results.length,
      results,
      mode,
      note,
    });
  } catch (e) {
    console.error(e);

    return NextResponse.json(
      {
        error: e instanceof Error ? e.message : "Request failed.",
      },
      { status: 500 }
    );
  }
}